language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=chatovod.test_settings
install:
  - pip install -e . --use-mirrors
  - pip install -r requirements/tests.txt Django==$DJANGO --use-mirrors
before_script:
  - flake8 chatovod
script:
  - coverage run --branch --source=chatovod `which django-admin.py` test chatovod
  - coverage report --omit="chatovod/test*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.3.7
    - python: "3.3"
      env: DJANGO=1.4.10
branches:
  only:
    - master
    - development
after_success: coveralls
